# Generated by Django 4.1.7 on 2023-03-20 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        # migrations.AddField(
        #     model_name='video',
        #     name='channel',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.channel'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='channel',
            name='profilephoto',
            field=models.ImageField(blank=True, upload_to='main_app/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='main_app/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to='main_app/static/uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        # migrations.CreateModel(
        #     name='Comment',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('content', models.TextField(max_length=500)),
        #         ('created_at', models.DateTimeField(default='')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #         ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.video')),
        #     ],
        # ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main_app.tag'),
        ),
        # migrations.CreateModel(
        #     name='Subscriber',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(default='')),
        #         ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.channel')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'unique_together': {('channel', 'user')},
        #     },
        # ),
    ]
