# Generated by Django 4.1.7 on 2023-03-20 15:02

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_comment_dislikes_comment_likes_video_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
